// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729091029_AddBarCatalogItems")]
    partial class AddBarCatalogItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.ActivityBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Guests")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeSlot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ActivityBookings");
                });

            modelBuilder.Entity("backend.Models.CatalogPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("CatalogPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Suites",
                            DisplayName = "Deluxe Room",
                            ItemKey = "suite_deluxe",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Suites",
                            DisplayName = "Ocean Pool Villa",
                            ItemKey = "suite_ocean",
                            Price = 480m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Suites",
                            DisplayName = "Honeymoon Suite",
                            ItemKey = "suite_honeymoon",
                            Price = 620m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Suites",
                            DisplayName = "Presidential Villa",
                            ItemKey = "suite_presidential",
                            Price = 1250m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Dining",
                            DisplayName = "Cherish Pizza Catch",
                            ItemKey = "dining_pizza",
                            Price = 34m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Dining",
                            DisplayName = "Fresh Truffle Entree",
                            ItemKey = "dining_truffle",
                            Price = 48m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Dining",
                            DisplayName = "Coconut Mousse on Pastry",
                            ItemKey = "dining_mousse",
                            Price = 24m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Dining",
                            DisplayName = "Spiced Fruit Tea Cup",
                            ItemKey = "dining_tea",
                            Price = 12m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Pool",
                            DisplayName = "Hour Pass",
                            ItemKey = "pool_hour",
                            Price = 240m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Pool",
                            DisplayName = "Day Pass",
                            ItemKey = "pool_day",
                            Price = 480m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Pool",
                            DisplayName = "Cabana Reserve",
                            ItemKey = "pool_cabana",
                            Price = 720m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Pool",
                            DisplayName = "Sunset Pool Party",
                            ItemKey = "pool_sunset",
                            Price = 960m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Events",
                            DisplayName = "Traditional Wedding",
                            ItemKey = "wedding_traditional",
                            Price = 240000m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Events",
                            DisplayName = "Beachfront Wedding",
                            ItemKey = "wedding_beachfront",
                            Price = 320000m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Events",
                            DisplayName = "Rainforest Wedding",
                            ItemKey = "wedding_rainforest",
                            Price = 280000m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Events",
                            DisplayName = "Luxury Wedding",
                            ItemKey = "wedding_luxury",
                            Price = 450000m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Bar",
                            Description = "Handcrafted drinks prepared by expert mixologists.",
                            DisplayName = "Signature Cocktails",
                            ItemKey = "bar_cocktail_1",
                            Price = 450m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Bar",
                            Description = "Zero-proof creations bursting with flavor.",
                            DisplayName = "Premium Mocktails",
                            ItemKey = "bar_mocktail_1",
                            Price = 300m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Bar",
                            Description = "Curated vintages from renowned vineyards.",
                            DisplayName = "Wine Selection",
                            ItemKey = "bar_wine_1",
                            Price = 950m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Bar",
                            Description = "Rare whiskeys, cognacs, and fine liqueurs.",
                            DisplayName = "Spirits",
                            ItemKey = "bar_spirits_1",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Bar",
                            Description = "Locally sourced artisanal craft beers.",
                            DisplayName = "Craft Brews",
                            ItemKey = "bar_cocktail_2",
                            Price = 380m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Bar",
                            Description = "A refreshing mix of pineapple, mango, and passionfruit.",
                            DisplayName = "Tropical Punch",
                            ItemKey = "bar_mocktail_2",
                            Price = 280m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Bar",
                            Description = "Premium sparkling champagnes imported directly from France.",
                            DisplayName = "Champagne Select",
                            ItemKey = "bar_wine_2",
                            Price = 1850m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Bar",
                            Description = "A selection of fine and rare single malt whiskeys.",
                            DisplayName = "Rare Vintage Malt",
                            ItemKey = "bar_spirits_2",
                            Price = 2400m
                        });
                });

            modelBuilder.Entity("backend.Models.ContactInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactInquiries");
                });

            modelBuilder.Entity("backend.Models.EventInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Guests")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EventInquiries");
                });

            modelBuilder.Entity("backend.Models.LoungeReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<string>("Occasion")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SeatingPreference")
                        .HasColumnType("longtext");

                    b.Property<string>("SpecialRequest")
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LoungeReservations");
                });

            modelBuilder.Entity("backend.Models.PoolBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Package")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeSlot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PoolBookings");
                });

            modelBuilder.Entity("backend.Models.SuiteBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Guests")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SuiteId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SuiteBookings");
                });

            modelBuilder.Entity("backend.Models.TableReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Guests")
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TableReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
